# 데이터 수집

In [36]:
import yfinance as yf

# 1. 애플(AAPL)의 주식 티커 데이터 가져오기
symbol = 'AAPL'
ticker = yf.Ticker(symbol)

ticker_info = ticker.info
ticker_info

# 2. 주가 데이터 가져오기 (최근 1년 간의 일일 주가 데이터)
# stock_data = stock.history(period='1y')
# stock_data

{'address1': 'One Apple Park Way',
 'city': 'Cupertino',
 'state': 'CA',
 'zip': '95014',
 'country': 'United States',
 'phone': '(408) 996-1010',
 'website': 'https://www.apple.com',
 'industry': 'Consumer Electronics',
 'industryKey': 'consumer-electronics',
 'industryDisp': 'Consumer Electronics',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': 'Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide. The company offers iPhone, a line of smartphones; Mac, a line of personal computers; iPad, a line of multi-purpose tablets; and wearables, home, and accessories comprising AirPods, Apple TV, Apple Watch, Beats products, and HomePod. It also provides AppleCare support and cloud services; and operates various platforms, including the App Store that allow customers to discover and download applications and digital content, such as books, music, video, games, and podcasts, as well as advertising services include third-party licensing arrangements and its own advertising platforms. In addition, the company offers various subscription-based services, such as Apple Arcade, a game subscription service; Apple Fitness+, a personalized fitness service; Apple Music, which offers users a curated listening experience with on-demand radio stations; Apple News+, a subscription news and magazine service; Apple TV+, which offers exclusive original content; Apple Card, a co-branded credit card; and Apple Pay, a cashless payment service, as well as licenses its intellectual property. The company serves consumers, and small and mid-sized businesses; and the education, enterprise, and government markets. It distributes third-party applications for its products through the App Store. The company also sells its products through its retail and online stores, and direct sales force; and third-party cellular network carriers, wholesalers, retailers, and resellers. Apple Inc. was founded in 1976 and is headquartered in Cupertino, California.',
 'fullTimeEmployees': 164000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Timothy D. Cook',
   'age': 63,
   'title': 'CEO & Director',
   'yearBorn': 1961,
   'fiscalYear': 2024,
   'totalPay': 16520856,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Jeffrey E. Williams',
   'age': 60,
   'title': 'Chief Operating Officer',
   'yearBorn': 1964,
   'fiscalYear': 2024,
   'totalPay': 5020737,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Katherine L. Adams',
   'age': 60,
   'title': 'Senior VP, General Counsel & Secretary',
   'yearBorn': 1964,
   'fiscalYear': 2024,
   'totalPay': 5022182,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': "Ms. Deirdre  O'Brien",
   'age': 57,
   'title': 'Chief People Officer & Senior VP of Retail',
   'yearBorn': 1967,
   'fiscalYear': 2024,
   'totalPay': 5022182,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Kevan  Parekh',
   'age': 52,
   'title': 'Senior VP & CFO',
   'yearBorn': 1972,
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Chris  Kondo',
   'title': 'Senior Director of Corporate Accounting',
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Suhasini  Chandramouli',
   'title': 'Director of Investor Relations',
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Kristin Huguet Quayle',
   'title': 'Vice President of Worldwide Communications',
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Greg  Joswiak',
   'title': 'Senior Vice President of Worldwide Marketing',
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Adrian  Perica',
   'age': 50,
   'title': 'Vice President of Corporate Development',
   'yearBorn': 1974,
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 7,
 'boardRisk': 1,
 'compensationRisk': 3,
 'shareHolderRightsRisk': 1,
 'overallRisk': 1,
 'governanceEpochDate': 1748736000,
 'compensationAsOfEpochDate': 1735603200,
 'irWebsite': 'http://investor.apple.com/',
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 201.45,
 'open': 200.6,
 'dayLow': 200.57,
 'dayHigh': 204.35,
 'regularMarketPreviousClose': 201.45,
 'regularMarketOpen': 200.6,
 'regularMarketDayLow': 200.57,
 'regularMarketDayHigh': 204.35,
 'dividendRate': 1.04,
 'dividendYield': 0.52,
 'exDividendDate': 1747008000,
 'payoutRatio': 0.1558,
 'fiveYearAvgDividendYield': 0.56,
 'beta': 1.211,
 'trailingPE': 31.324575,
 'forwardPE': 24.388687,
 'volume': 51337372,
 'regularMarketVolume': 51337372,
 'averageVolume': 61653207,
 'averageVolume10days': 52211490,
 'averageDailyVolume10Day': 52211490,
 'bid': 190.52,
 'ask': 210.7,
 'bidSize': 1,
 'askSize': 1,
 'marketCap': 3027038633984,
 'fiftyTwoWeekLow': 169.21,
 'fiftyTwoWeekHigh': 260.1,
 'priceToSalesTrailing12Months': 7.5606785,
 'fiftyDayAverage': 202.9268,
 'twoHundredDayAverage': 224.87386,
 'trailingAnnualDividendRate': 1.0,
 'trailingAnnualDividendYield': 0.004964011,
 'currency': 'USD',
 'tradeable': False,
 'enterpriseValue': 3076731961344,
 'profitMargins': 0.24301,
 'floatShares': 14911480604,
 'sharesOutstanding': 14935799808,
 'sharesShort': 105169332,
 'sharesShortPriorMonth': 113127198,
 'sharesShortPreviousMonthDate': 1744675200,
 'dateShortInterest': 1747267200,
 'sharesPercentSharesOut': 0.0069999998,
 'heldPercentInsiders': 0.02085,
 'heldPercentInstitutions': 0.62889,
 'shortRatio': 1.97,
 'shortPercentOfFloat': 0.0069999998,
 'impliedSharesOutstanding': 15118999552,
 'bookValue': 4.471,
 'priceToBook': 45.329903,
 'lastFiscalYearEnd': 1727481600,
 'nextFiscalYearEnd': 1759017600,
 'mostRecentQuarter': 1743206400,
 'earningsQuarterlyGrowth': 0.048,
 'netIncomeToCommon': 97294000128,
 'trailingEps': 6.47,
 'forwardEps': 8.31,
 'lastSplitFactor': '4:1',
 'lastSplitDate': 1598832000,
 'enterpriseToRevenue': 7.685,
 'enterpriseToEbitda': 22.156,
 '52WeekChange': -0.048810244,
 'SandP52WeekChange': 0.11395991,
 'lastDividendValue': 0.26,
 'lastDividendDate': 1747008000,
 'quoteType': 'EQUITY',
 'currentPrice': 202.67,
 'targetHighPrice': 300.0,
 'targetLowPrice': 170.62,
 'targetMeanPrice': 228.85326,
 'targetMedianPrice': 232.5,
 'recommendationMean': 2.1087,
 'recommendationKey': 'buy',
 'numberOfAnalystOpinions': 40,
 'totalCash': 48497999872,
 'totalCashPerShare': 3.247,
 'ebitda': 138865999872,
 'totalDebt': 98186002432,
 'quickRatio': 0.68,
 'currentRatio': 0.821,
 'totalRevenue': 400366010368,
 'debtToEquity': 146.994,
 'revenuePerShare': 26.455,
 'returnOnAssets': 0.23809999,
 'returnOnEquity': 1.38015,
 'grossProfits': 186699005952,
 'freeCashflow': 97251500032,
 'operatingCashflow': 109555998720,
 'earningsGrowth': 0.078,
 'revenueGrowth': 0.051,
 'grossMargins': 0.46632,
 'ebitdaMargins': 0.34685,
 'operatingMargins': 0.31028998,
 'financialCurrency': 'USD',
 'symbol': 'AAPL',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Nasdaq Real Time Price',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'cryptoTradeable': False,
 'postMarketChangePercent': 0.113483,
 'postMarketPrice': 202.9,
 'postMarketChange': 0.229996,
 'regularMarketChange': 1.22,
 'regularMarketDayRange': '200.57 - 204.35',
 'fullExchangeName': 'NasdaqGS',
 'averageDailyVolume3Month': 61653207,
 'fiftyTwoWeekLowChange': 33.45999,
 'fiftyTwoWeekLowChangePercent': 0.19774239,
 'fiftyTwoWeekRange': '169.21 - 260.1',
 'fiftyTwoWeekHighChange': -57.430008,
 'fiftyTwoWeekHighChangePercent': -0.22079971,
 'fiftyTwoWeekChangePercent': -4.8810244,
 'dividendDate': 1747267200,
 'earningsTimestamp': 1746131400,
 'earningsTimestampStart': 1753873140,
 'earningsTimestampEnd': 1754308800,
 'earningsCallTimestampStart': 1746133200,
 'earningsCallTimestampEnd': 1746133200,
 'isEarningsDateEstimate': True,
 'epsTrailingTwelveMonths': 6.47,
 'epsForward': 8.31,
 'epsCurrentYear': 7.18956,
 'priceEpsCurrentYear': 28.189486,
 'fiftyDayAverageChange': -0.25680542,
 'fiftyDayAverageChangePercent': -0.0012655077,
 'twoHundredDayAverageChange': -22.203857,
 'twoHundredDayAverageChangePercent': -0.09873917,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 0,
 'averageAnalystRating': '2.1 - Buy',
 'corporateActions': [],
 'postMarketTime': 1749599997,
 'regularMarketTime': 1749585600,
 'exchange': 'NMS',
 'messageBoardId': 'finmb_24937',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'gmtOffSetMilliseconds': -14400000,
 'market': 'us_market',
 'esgPopulated': False,
 'marketState': 'PREPRE',
 'hasPrePostMarketData': True,
 'firstTradeDateMilliseconds': 345479400000,
 'shortName': 'Apple Inc.',
 'longName': 'Apple Inc.',
 'regularMarketChangePercent': 0.60561,
 'regularMarketPrice': 202.67,
 'displayName': 'Apple',
 'trailingPegRatio': 1.8291}

In [37]:
# 2. 주가 데이터 가져오기 (최근 1년 간의 일일 주가 데이터)
ticker_data = stock.history(period='1y')
ticker_data

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2024-06-11 00:00:00-04:00,192.748571,206.195693,192.728675,206.185730,172373300,0.0,0.0
2024-06-12 00:00:00-04:00,206.404722,219.175002,205.936908,212.078201,198134300,0.0,0.0
2024-06-13 00:00:00-04:00,213.740409,215.741048,210.615026,213.242737,97862700,0.0,0.0
2024-06-14 00:00:00-04:00,212.854540,214.168387,210.316407,211.500870,70122700,0.0,0.0
2024-06-17 00:00:00-04:00,212.376781,217.930808,211.729813,215.661423,93728300,0.0,0.0
...,...,...,...,...,...,...,...
2025-06-04 00:00:00-04:00,202.910004,206.240005,202.100006,202.820007,43604000,0.0,0.0
2025-06-05 00:00:00-04:00,203.500000,204.750000,200.149994,200.630005,55126100,0.0,0.0
2025-06-06 00:00:00-04:00,203.000000,205.699997,202.050003,203.919998,46607700,0.0,0.0
2025-06-09 00:00:00-04:00,204.389999,206.000000,200.020004,201.449997,72862600,0.0,0.0
2025-06-10 00:00:00-04:00,200.600006,204.350006,200.570007,202.669998,54553200,0.0,0.0

In [38]:
ticker_info.get('shortName')

'Apple Inc.'

In [ ]:
# 현재 날짜
from datetime import datetime
today = datetime.today().strftime('%Y-%m-%d')

# 기본 정보
ticker_info = ticker.info    

name = ticker_info.get('longName', 'N/A')                 # 회사 이름
exchange = ticker_info.get('marketCap', 'N/A')            # 거래소(시장)
industry = ticker_info.get('industry', 'N/A')             # 산업
sector = ticker_info.get('sector', 'N/A')                 # 섹터
employees = ticker_info.get('fullTimeEmployees', 'N/A')   # 총 직원 수
current_price = ticker_info.get('currentPrice', 'N/A')    # 최근 주가
market_cap = ticker_info.get('enterpriseValue', 'N/A')    # 기업 가치 (시가총액)

- 보고서 생성 템플릿

In [40]:
# 마크다운 형식의 보고서 생성
report = f"""
# {name} ({ticker}) 기업 정보 보고서

**작성일**: {today}

---
## 1. 회사 정보
- **종목명**: {name}
- **거래소(시장)**: {exchange}
- **산업**: {industry}
- **섹터**: {sector}
- **총 직원 수**: {employees}

---

## 2. 주식 및 기업 가치
- **최근 주가**: {current_price} USD
- **기업 가치 (시가총액)**: {market_cap:,} USD

"""

In [41]:
# 보고서 출력
print(report)

# Apple Inc. (yfinance.Ticker object <AAPL>) 기업 정보 보고서

**작성일**: 2025-06-11

---
## 1. 회사 정보
- **종목명**: Apple Inc.
- **거래소(시장)**: 3027038633984
- **산업**: Consumer Electronics
- **섹터**: Technology
- **총 직원 수**: 164000

---

## 2. 주식 및 기업 가치
- **최근 주가**: 202.67 USD
- **기업 가치 (시가총액)**: 3,076,731,961,344 USD

# 재무재표 데이터 수집

In [56]:
income_stmt = ticker.income_stmt.loc[[
    'Total Revenue', 'Gross Profit','Operating Income', 'Net Income']].iloc[:, :4].to_markdown()
print(income_stmt)

|                  |   2024-09-30 00:00:00 |   2023-09-30 00:00:00 |   2022-09-30 00:00:00 |   2021-09-30 00:00:00 |
|:-----------------|----------------------:|----------------------:|----------------------:|----------------------:|
| Total Revenue    |           3.91035e+11 |           3.83285e+11 |           3.94328e+11 |           3.65817e+11 |
| Gross Profit     |           1.80683e+11 |           1.69148e+11 |           1.70782e+11 |           1.52836e+11 |
| Operating Income |           1.23216e+11 |           1.14301e+11 |           1.19437e+11 |           1.08949e+11 |
| Net Income       |           9.3736e+10  |           9.6995e+10  |           9.9803e+10  |           9.468e+10   |

In [58]:
# 대차대조표를 마크다운 형식으로 변환
balance_sheet = ticker.balance_sheet.loc[['Total Assets', 
                                                'Total Liabilities Net Minority Interest',
                                                'Stockholders Equity']].iloc[:, :4].to_markdown()
print(balance_sheet)

|                                         |   2024-09-30 00:00:00 |   2023-09-30 00:00:00 |   2022-09-30 00:00:00 |   2021-09-30 00:00:00 |
|:----------------------------------------|----------------------:|----------------------:|----------------------:|----------------------:|
| Total Assets                            |            3.6498e+11 |           3.52583e+11 |           3.52755e+11 |           3.51002e+11 |
| Total Liabilities Net Minority Interest |            3.0803e+11 |           2.90437e+11 |           3.02083e+11 |           2.87912e+11 |
| Stockholders Equity                     |            5.695e+10  |           6.2146e+10  |           5.0672e+10  |           6.309e+10   |

In [59]:
# 현금 흐름표를 마크다운 형식으로 변환
cash_flow = ticker.cashflow.loc[['Operating Cash Flow', 
                                 'Investing Cash Flow',
                                 'Financing Cash Flow']].iloc[:, :4].to_markdown()
print(cash_flow)

|                     |   2024-09-30 00:00:00 |   2023-09-30 00:00:00 |   2022-09-30 00:00:00 |   2021-09-30 00:00:00 |
|:--------------------|----------------------:|----------------------:|----------------------:|----------------------:|
| Operating Cash Flow |           1.18254e+11 |           1.10543e+11 |           1.22151e+11 |           1.04038e+11 |
| Investing Cash Flow |           2.935e+09   |           3.705e+09   |          -2.2354e+10  |          -1.4545e+10  |
| Financing Cash Flow |          -1.21983e+11 |          -1.08488e+11 |          -1.10749e+11 |          -9.3353e+10  |

In [42]:
# 손익계산서 (Income Statement)
income_statement = stock.financials
print("손익계산서 (Income Statement):")
# print(income_statement)
print(type(income_statement))

손익계산서 (Income Statement):
<class 'pandas.core.frame.DataFrame'>

In [43]:
income_statement.head()  # 상위 5개 행 출력

,2024-09-30,2023-09-30,2022-09-30,2021-09-30,2020-09-30
Tax Effect Of Unusual Items,0.0,0.0,0.0,0.0,NaN
Tax Rate For Calcs,0.241,0.147,0.162,0.133,NaN
Normalized EBITDA,134661000000.0,125820000000.0,130541000000.0,123136000000.0,NaN
Net Income From Continuing Operation Net Minority Interest,93736000000.0,96995000000.0,99803000000.0,94680000000.0,NaN
Reconciled Depreciation,11445000000.0,11519000000.0,11104000000.0,11284000000.0,NaN

In [44]:
# 현금흐름표 (Cash Flow Statement)
cash_flow = stock.cashflow
print("\n현금흐름표 (Cash Flow Statement):")
# print(cash_flow)
print(type(cash_flow))

현금흐름표 (Cash Flow Statement):
<class 'pandas.core.frame.DataFrame'>

In [45]:
cash_flow.head()

,2024-09-30,2023-09-30,2022-09-30,2021-09-30,2020-09-30
Free Cash Flow,108807000000.0,99584000000.0,111443000000.0,92953000000.0,NaN
Repurchase Of Capital Stock,-94949000000.0,-77550000000.0,-89402000000.0,-85971000000.0,NaN
Repayment Of Debt,-9958000000.0,-11151000000.0,-9543000000.0,-8750000000.0,NaN
Issuance Of Debt,0.0,5228000000.0,5465000000.0,20393000000.0,NaN
Issuance Of Capital Stock,NaN,NaN,NaN,1105000000.0,880000000.0

In [46]:
# 최근 6개월 간의 주가 데이터를 가져오기 (기간 설정 가능: "1mo", "3mo", "6mo", "1y" 등)
# interval 옵션은 데이터 수집 간격을 의미 (e.g., "1d": 일간 데이터, "1wk": 주간 데이터, "1mo": 월간 데이터)
hist = stock.history(period="6mo", interval="1d")

# 주가 데이터 출력 (OHLC 및 거래량)
print(hist[['Open', 'High', 'Low', 'Close', 'Volume']])
# print(type(hist))

                                 Open        High         Low       Close  \
Date
2024-12-11 00:00:00-05:00  247.363284  250.196445  245.667363  245.896820
2024-12-12 00:00:00-05:00  246.295864  248.141418  245.088769  247.363297
2024-12-13 00:00:00-05:00  247.223631  248.690080  245.647432  247.532883
2024-12-16 00:00:00-05:00  247.393219  250.775061  247.054026  250.435867
2024-12-17 00:00:00-05:00  249.478183  253.219159  249.178902  252.869995
...                               ...         ...         ...         ...
2025-06-04 00:00:00-04:00  202.910004  206.240005  202.100006  202.820007
2025-06-05 00:00:00-04:00  203.500000  204.750000  200.149994  200.630005
2025-06-06 00:00:00-04:00  203.000000  205.699997  202.050003  203.919998
2025-06-09 00:00:00-04:00  204.389999  206.000000  200.020004  201.449997
2025-06-10 00:00:00-04:00  200.600006  204.350006  200.570007  202.669998

                             Volume
Date
2024-12-11 00:00:00-05:00  45205800
2024-12-12 00:00:00-05:00  32777500
2024-12-13 00:00:00-05:00  33155300
2024-12-16 00:00:00-05:00  51694800
2024-12-17 00:00:00-05:00  51356400
...                             ...
2025-06-04 00:00:00-04:00  43604000
2025-06-05 00:00:00-04:00  55126100
2025-06-06 00:00:00-04:00  46607700
2025-06-09 00:00:00-04:00  72862600
2025-06-10 00:00:00-04:00  54553200

[123 rows x 5 columns]

In [48]:
import pandas as pd
basic_info = pd.DataFrame.from_dict(
    ticker.info, orient='index', columns=['valus'])
basic_info
# basic_info = pd.DataFrame.from_dict(self.ticker.info, orient='index', columns=['Value'])
# df_dict = pd.DataFrame(stock_info, orient='index', columns='valus')

                                         valus
address1                    One Apple Park Way
city                                 Cupertino
state                                       CA
zip                                      95014
country                          United States
...                                        ...
longName                            Apple Inc.
regularMarketChangePercent             0.60561
regularMarketPrice                      202.67
displayName                              Apple
trailingPegRatio                        1.8291

[180 rows x 1 columns]